### ISSUE TITLE
Resolver exercício 05 e 06

### ISSUE THREAD

**Issue by carloseduardo95** [carloseduardo95/curso-java#1]
1.8.5 Exercício 05
Desenvolver uma classe chamada Computador com os seguintes atributos: marca, cor, modelo, numeroSerie, preço. Implementar os seguintes métodos:
Método	Descrição
imprimir()	Este método não retorna valor e deve imprimir os atributos na tela.
calcularValor()	Não retorna valor e deverá verificar as seguintes condições: Caso a marca seja HP acrescentar 30% no seu preço. Caso a marca seja IBM acrescentar 50% no seu preço. Caso a marca seja qualquer outra manter o preço original.
alterarValor()	Este método recebe um valor como parâmetro. Atribuir este valor ao atributo preço, caso o valor do parâmetro recebido seja maior que 0. Caso este seja maior que 0 o método alterarValor() deverá além de atribuir o valor ao atributo preço retornar 1. Caso contrário não atribuir o valor ao atributo preço e retornar 0.
O programa 01.29 apresenta o resultado do exercício 05.

1.8.6 Exercício 06
Desenvolver uma segunda classe Java chamada PrincipalComputador com a seguinte estrutura:
* Criar o método main() conforme o padrão da linguagem Java. 
* Criar um objeto da classe Computador e atribuir valores aos seus atributos. Atribuir HP para o atributo marca.
* Executar o método imprimir() e analisar o que será impresso na tela. 
* Executar o método calcularValor(). 
* Executar o método imprimir() e analisar o que será impresso na tela.
* Criar um segundo objeto e atribuir valores aos seus atributos. Atribuir IBM para o atributo marca do novo objeto.
* Executar o método calcularValor() do novo objeto. 
* Executar o método imprimir() do novo objeto e analisar o que será impresso na tela. 
* Executar para o novo objeto o método alterarValor() com um valor positivo. 
* Verificar no método main() o retorno do método alterarValor() e mostrar a mensagem de "Alterado” caso este retorne 1 e valor "Não Alterado” caso este retorne 0.
* Executar para o novo objeto o método alterarValor() com um valor negativo. 
* Verificar no método main() o retorno do método alterarValor() e mostrar a mensagem de "Valor Alterado” caso este retorne 1 e "valor Não Alterado” caso este retorne 0. 
* Executar para o novo objeto o método imprimir() e analisar o que será impresso na tela.
O programa 01.30 apresenta o resultado do exercício 06.

**Comment by carloseduardo95** [comment]
@lucasmaciel1996 utilizar classe Computador e PrincipalComputador do pacote Exercicios1ao12

**Comment by lucasmaciel1996** [comment]
@carloseduardo95  Utilizar o conceito de polimorfismo ??

**Comment by carloseduardo95** [comment]
Apenas herança nesse exercício.

**Comment by lucasmaciel1996** [comment]
OK,
